-- Setup for Todo List Application Database in Supabase

-- Create the todos table
CREATE TABLE IF NOT EXISTS public.todos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  text TEXT NOT NULL,
  completed BOOLEAN DEFAULT FALSE NOT NULL
);

-- Add comment to the table
COMMENT ON TABLE public.todos IS 'Stores todo items for the todo list application';

-- Add comments to columns
COMMENT ON COLUMN public.todos.id IS 'Unique identifier for each todo item';
COMMENT ON COLUMN public.todos.created_at IS 'Timestamp when the todo was created';
COMMENT ON COLUMN public.todos.text IS 'The content of the todo item';
COMMENT ON COLUMN public.todos.completed IS 'Whether the todo item has been completed';

-- Set up Row Level Security (RLS)
-- This is a basic setup that allows all operations
-- In a real app with authentication, you would want to restrict this
ALTER TABLE public.todos ENABLE ROW LEVEL SECURITY;

-- Create a policy that allows all operations for now
-- You can modify this later to restrict based on user authentication
CREATE POLICY "Allow all operations for now" ON public.todos
  FOR ALL
  USING (true)
  WITH CHECK (true);

-- Create an index on created_at for faster sorting
CREATE INDEX IF NOT EXISTS todos_created_at_idx ON public.todos (created_at DESC);

-- Create an index on completed status for faster filtering
CREATE INDEX IF NOT EXISTS todos_completed_idx ON public.todos (completed);

-- Insert some sample data
INSERT INTO public.todos (text, completed)
VALUES 
  ('Buy groceries', false),
  ('Finish project', false),
  ('Call mom', true),
  ('Go for a run', false),
  ('Read a book', false); 